name: Fetch Retro Funding Metrics

on:
  workflow_dispatch:

jobs:
  fetch-metrics:
    runs-on: ubuntu-latest
    env:
      OSO_API_KEY: ${{ secrets.OSO_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          
      - name: Run fetch-metrics script
        id: fetch-metrics
        run: |
          source .venv/bin/activate
          python src/main.py '${{ inputs.input_data }}'
        shell: bash
        continue-on-error: true
        
      - name: Check script execution
        if: steps.fetch-metrics.outcome == 'failure'
        run: |
          echo "::error::Script execution failed"
          exit 1
          
      - name: Process output
        if: success()
        run: |
          echo "Gist output:"
          echo "${{ steps.fetch-metrics.outputs.stdout }}"
          if [ -n "${{ steps.fetch-metrics.outputs.stderr }}" ]; then
            echo "Warnings/Debug info:"
            echo "${{ steps.fetch-metrics.outputs.stderr }}" 
